/**
 * ⚠️ TEMPORARY PLACEHOLDER - DO NOT USE IN PRODUCTION
 *
 * This file is a temporary placeholder created during the migration from bk_nextjs.
 * It will be auto-generated by Scaffold-ETH/Foundry deployment scripts.
 *
 * TODO: Replace with actual deployed contracts when migrating blockchain functionality
 * See: packages/bk_nextjs/contracts/deployedContracts.ts for reference
 *
 * Migration checklist:
 * - [ ] Run foundry deployment scripts (pnpm contracts:deploy)
 * - [ ] Verify contract addresses on target networks
 * - [ ] Update contract ABIs to match latest Solidity code
 * - [ ] Test all contract interactions
 * - [ ] Remove this placeholder and warning
 *
 * Expected contracts to migrate:
 * - MockHumanPassport (Human Passport verification)
 * - StudyRegistry (Clinical trial registry)
 * - ResearchFundingEscrow (Funding management)
 * - HealthIdentitySBT (Patient identity SBT)
 * - StudyParticipationSBT (Enrollment SBT)
 * - MockUSDC (Test token)
 */

import { GenericContractsDeclaration } from "./types";

/**
 * Empty contract declaration - will be populated by deployment scripts
 */
const deployedContracts = {} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
