/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "./types";

const deployedContracts = {
  31337: {
    AgeVerifier: {
      address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      abi: [
        {
          type: "function",
          name: "verify",
          inputs: [
            {
              name: "proof",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "minAge",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "maxAge",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "verifyView",
          inputs: [
            {
              name: "proof",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "minAge",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "maxAge",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "event",
          name: "ProofVerified",
          inputs: [
            {
              name: "prover",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "minAge",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "maxAge",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "success",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    StudyRegistryImpl: {
      address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_ageVerifier",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "ageVerifier",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AgeVerifier",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "closeStudyRecruitment",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getStudyCriteria",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StudyRegistryImpl.EligibilityCriteria",
              components: [
                {
                  name: "minAge",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "maxAge",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "requiresAgeProof",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getStudyDetails",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct IStudyRegistry.Study",
              components: [
                {
                  name: "studyId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "researcher",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "region",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "compensationDetails",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "criteriaURI",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTotalStudies",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getVerifiedApplicantsCount",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasAddressApplied",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_applicant",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasApplied",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "publishStudy",
          inputs: [
            {
              name: "_region",
              type: "string",
              internalType: "string",
            },
            {
              name: "_compensationDetails",
              type: "string",
              internalType: "string",
            },
            {
              name: "_criteriaURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setStudyCriteria",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_minAge",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "_maxAge",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "studies",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "studyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "researcher",
              type: "address",
              internalType: "address",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "region",
              type: "string",
              internalType: "string",
            },
            {
              name: "compensationDetails",
              type: "string",
              internalType: "string",
            },
            {
              name: "criteriaURI",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "studyCriteria",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "minAge",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "maxAge",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "requiresAgeProof",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "submitAnonymousApplication",
          inputs: [
            {
              name: "_studyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_ageProof",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "verifiedApplicantsCount",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "AnonymousApplicationSubmitted",
          inputs: [
            {
              name: "studyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "applicantCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StudyCriteriaSet",
          inputs: [
            {
              name: "studyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "minAge",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "maxAge",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StudyPublished",
          inputs: [
            {
              name: "studyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "researcher",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "region",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyApplied",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidStudyId",
          inputs: [],
        },
        {
          type: "error",
          name: "ProofVerificationFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "StudyNotRecruiting",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
