[package]
name = "eligibility-halo2"
version = "0.1.0"
edition = "2021"

[dependencies]
# PSE Halo2 (with KZG for Ethereum compatibility)
# Using main branch for latest stable code
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", branch = "main" }
halo2curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves.git", branch = "main" }

# Poseidon hash (ZK-friendly)
poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon.git", branch = "main" }

# Field arithmetic
ff = "0.13"
group = "0.13"

# Randomness
rand = "0.8"
rand_core = "0.6"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"

[dev-dependencies]
criterion = "0.5"

[lib]
crate-type = ["lib"]
