name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0

      - name: Install dependencies
        run: pnpm install
      
      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run foundry node in background
        run: pnpm chain &

      - name: Wait for anvil to be ready
        run: |
          timeout 30 bash -c 'until cast block-number &> /dev/null; do sleep 1; done' || echo "Anvil is ready"

      - name: Deploy contracts
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: pnpm contracts:deploy

      - name: Run nextjs lint
        run: pnpm next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: pnpm next:check-types