/**
 * Generated ABIs from Foundry Artifacts
 *
 * Auto-generated by scripts/extract-abis.js
 * DO NOT EDIT MANUALLY
 *
 * To regenerate: yarn extract-abis
 */

export const GENERATED_ABIS = {} as const;

export type ContractName = 'StudyRegistryImpl' | 'AgeVerifier' | 'StudyParticipationSBT' | 'StudyEnrollmentData' | 'CommitmentVault' | 'CommitmentVaultFactory' | 'TrialAccessNFT' | 'ComplianceScore' | 'EligibilityCodeVerifier';
